### PR TITLE
Colour generation improvements

### PR DESCRIPTION
**Pull request by Gregam3**
### Description
This PR is linked to issue #237 
Changed colour generation algorithm adding clarity and changing how it divides colours up

### Which areas of Code needs reviewing
- [x] Backend
- [ ] Swagger 
- [ ] Frontend

### Where should the reviewer start (Optional)
Colour.java

### Specific Reviewer testing steps (Optional)
Loads heat map a number of times on different locations

### CODE REVIEW

**Comment by Gregam3** [comment]
`RED_SCALING` was already a constant I just forgot to remove the old variable, IP changed back to AWS ip.

**Comment by jamesfernando94** [comment]
*[a discussion](https://reviewable.io/reviews/gregam3/asegroup1/238#-LTNksMiDqm-4bdJ311v:-LTNksMiDqm-4bdJ311w:b114vxq) (no related file):*
### All Code
- [ ] Looked over the code for errors
- [x] The code is written using coding standards/guidelines
- [x] There is no repeated code
- [x] No functions are too big which can't  be split up/made smaller
- [x] No classes are too big which can't be abstracted/generalised
- [x] Proper naming conventions have been used throughout the code i.e. camelCase
- [x] No lines are too long to fit on the screen i.e. longer than 80 character widths
- [x] There is no commented out code
- [ ] All the files are in the correct folder
- [x] There are no unused files
- [x] There are no typos/spelling mistakes
- [x] Can any code be replaced with a library or built-in function
- [x] There aren't any magic strings which can be removed/substituted
- [x] Exceptions are only used for exceptional cases i.e. during the normal course of operation exceptions are not used
- [x] There are no ide files included


### Java/Springboot
- [ ] Are all complex public functions Javadoc commented
- [x] Are all Controller methods properly documented using @Api tags and javadoc comments
- [x] The project builds successfully
- [x] The project starts correctly
- [x] All the unit tests pass
- [x] There aren't any unused imports
- [ ] There are no intellij/eclipse errors

---

**Comment by Gregam3** [comment]
@jamesfernando94 I've made some of the changes you've requested. 

In response to the others, 
`Shouldn't this need a call to isColourValueValid() before this?`
as we check this in all of the setters and the setters are called in the constructor this is a superfluous check.

And those methods are public as although we don't use them out of the class yet we may do at some point and the concept of a colour object should have those accessors and mutators available.

**Comment by jamesfernando94** [comment]
@Gregam3 
> `Shouldn't this need a call to isColourValueValid() before this?`
> as we check this in all of the setters and the setters are called in the constructor this is a superfluous check.
Makes Sense
> And those methods are public as although we don't use them out of the class yet we may do at some point and the concept of a colour object should have those accessors and mutators available.
ok then can we suppress the intellij warnings then
Also Tell me when you want it reviewed

**Comment by jamesfernando94** [comment]
Also I think the file conflicts are simple enough to be fixed on the merge

**Pull request merged**
